baseURL = 'https://toto.photo/'
locale = 'en-us'
title = 'Toto Tvalavadze'
disableKinds = ['taxonomy', 'term']

[params]
  author = "Toto Tvalavadze"
  description = "Photography portfolio exploring the intersection of concrete narratives and personal interpretation through Liminal Realism."
  twitter = "@totocaster"
  instagram = "https://instagram.com/totocaster"
