baseURL = 'https://totocaster.com/'
languageCode = 'en-us'
title = 'Toto Tvalavadze'

[params]
  author = "Toto Tvalavadze"
  twitter = "@totocaster"
  instagram = "https://instagram.com/totocaster"
  membershipURL = "https://ttvl.co/membership"

[permalinks]
  maquettes = "/maquettes/:filename/"